apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: node171766560
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: node171766560 
  name: node171766560
spec:
  port:
    targetPort: 3001 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: node171766560
    weight: 100 
